### ISSUE TITLE
Too verbose

### ISSUE THREAD

**Issue by mherrmann** [brave/pull-merge#96]
I just got a [lengthy comment](https://github.com/brave/brave-core/pull/22689#issuecomment-2008969315) by puLL-merge on a brave-core PR. I understand the motivation, but feel that this adds more noise than it is worth. PRs are often hard to read with reviewer comments etc. anyways. puLL-merge just adds to this. My preference would be for puLL-merge to not create such comments automatically.

**Comment by mherrmann** [comment]
I see now that the comments seem not to be created for all PRs, but just for (I suspect) one that puLL-merge deems relevant for security. Still, maybe the comment could be made less verbose?

**Comment by thypon** [comment]
https://github.com/brave/pull-merge/blob/main/src/anthropicExplainPatch.js#L21 the comment is maximum 2000 token, and, In `brave-core` the `amplification` factor is `4` which means that the patch itself needs to be at least 8000 token long to trigger (consider a token ~ like a word/symbol for the sake of the discussion).

This also means that the patch is 4 times less time consuming to read in the summarized format.
The security-action and puLL-Merge usually trigger together because complex code/lengthy code is more prone
to contain security faults, so there is a strong correlation on when they trigger.

FYI the comment is not for the code writer that has perfect domain knowledge, and the code they wrote make perfect sense to them. But for the reviewer to have an automated brief on what they are gonna read, and make some sense of differential patches.

We can tweak these numbers, but I feel we are in a good spot ATM.
